Deb: Add support for legacy init systems again
Partially reverts commit a4cc6fb91f3855e0ed803a6e1762440cfcf8cb5c.

While all current versions of Linux have systemd, support for traditional
init.d is still needed e.g. on Linux subsystem on Windows, kFreeBSD and
special variants of Debian/Ubuntu that for other reasons don't have
systemd.

Thus, re-introduce the init file that was remove, but this time with
then name 'mariadb'.

Supporting traditional sysv init in paraller with systemd is easy, since
Debian has facilities for it.

Also simplify and update salsa-ci.yml install/upgrade testing works
for all previous MariaDB and MySQL releases without any excess quirks.

Note that in fresh installs the salsa-ci.yml needs to run command
'service mariadb status' to control the service, while on upgrades
it is enough to run 'service mysql status', since the init.d/mysql
file is left behind from previous install, along with some other
config files such as /etc/default/mysql and /etc/mysql/* stuff.

Conflicts:
      debian/mariadb-server-10.4.postinst
      debian/mariadb-server-10.4.postrm
      debian/salsa-ci.yml
      debian/tests/smoke

diff --git a/debian/mariadb-server-10.4.postinst b/debian/mariadb-server-10.4.postinst
--- a/debian/mariadb-server-10.4.postinst
+++ b/debian/mariadb-server-10.4.postinst
@@ -16,17 +16,13 @@ ERR_LOGGER="logger -p daemon.err -t mariadb-server-$MAJOR_VER.postinst -i"
 # the install, rather than failing silently and leaving a broken install.
 set -o pipefail
 
-invoke() {
-  systemctl $1 mysql
-}
-
 case "$1" in
   configure)
-    # This is needed because mysql_install_db removes the pid file in /var/run
+    # This is needed because mysql_install_db removes the pid file in /run
     # and because changed configuration options should take effect immediately.
     # In case the server wasn't running at all it should be ok if the stop
-    # script fails. I can't tell at this point because of the cleaned /var/run.
-    set +e; invoke stop; set -e
+    # script fails. I can't tell at this point because of the cleaned /run.
+    set +e; invoke-rc.d mysql stop; set -e
 
     mysql_statedir=/usr/share/mysql
     mysql_datadir=/var/lib/mysql
@@ -164,8 +160,9 @@ EOF
   triggered)
     if [ -d /run/systemd/system ]; then
       systemctl --system daemon-reload
+    else
+      invoke-rc.d mysql restart
     fi
-    invoke restart
   ;;
 
   *)
diff --git a/debian/mariadb-server-10.4.postrm b/debian/mariadb-server-10.4.postrm
--- a/debian/mariadb-server-10.4.postrm
+++ b/debian/mariadb-server-10.4.postrm
@@ -9,24 +9,29 @@ MYADMIN="/usr/bin/mysqladmin --defaults-file=/etc/mysql/debian.cnf"
 
 # Try to stop the server in a sane way. If it does not success let the admin
 # do it himself. No database directories should be removed while the server
-# is running!
+# is running! Another mysqld in e.g. a different chroot is fine for us.
 stop_server() {
-  # Return immediately if there are no mysql processes running
+  # Return immediately if there are no mysql processes running on a host
+  # (leave containerized processes with the same name in other namespaces)
   # as there is no point in trying to shutdown in that case.
   # Compatibility with versions that ran 'mariadbd'
   if ! pgrep -x --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
 
   set +e
-  systemctl stop mysql
+  invoke-rc.d mysql stop
   errno=$?
   set -e
 
-  if [ "$?" != 0 ]; then
-    echo "Trying to stop the MySQL server resulted in exitcode $?." 1>&2
+  # 0=ok, systemctl could emit exit code 100=no init script (fresh install)
+  if [ "$errno" != 0 -a "$errno" != 100 ]; then
+    echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+    echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
     echo "Stop it yourself and try again!" 1>&2
+    db_stop
     exit 1
   fi
 }
+
 
 case "$1" in
   purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
@@ -57,18 +62,23 @@ if [ "$1" = "purge" -a ! \( -x /usr/sbin/mysqld -o -L /usr/sbin/mysqld \) ]; the
     # never remove the debian.cnf when the databases are still existing
     # else we ran into big trouble on the next install!
     rm -f /etc/mysql/debian.cnf
-    # Remove all contents from /var/lib/mysql except if it's a
-    # directory with file system data. See #829491 for details and
-    # #608938 for potential mysql-server leftovers which erroneously
-    # had been renamed.
-    find /var/lib/mysql -mindepth 1 \
-         -not -path '*/lost+found/*'     -not -name 'lost+found' \
-         -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
-         -delete
-    # "|| true" still needed as rmdir still exits with non-zero if
-    # /var/lib/mysql is a mount point
-    rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
-    rm -rf /var/run/mysqld # this directory is created by the init script, don't leave behind
+    # Attempt removal only if the directory hasn't already been removed
+    # by dpkg to avoid failing on "No such file or directory" errors.
+    if [ -d /var/lib/mysql ]; then
+      # Remove all contents from /var/lib/mysql except if it's a
+      # directory with file system data. See #829491 for details and
+      # #608938 for potential mysql-server leftovers which erroneously
+      # had been renamed.
+      find /var/lib/mysql -mindepth 1 \
+           -not -path '*/lost+found/*'     -not -name 'lost+found' \
+           -not -path '*/lost@002bfound/*' -not -name 'lost@002bfound' \
+           -delete
+
+      # "|| true" still needed as rmdir still exits with non-zero if
+      # /var/lib/mysql is a mount point
+      rmdir --ignore-fail-on-non-empty /var/lib/mysql || true
+    fi
+    rm -rf /run/mysqld # this directory is created by the init script, don't leave behind
     userdel mysql || true
   fi
 
diff --git a/debian/mariadb-server-10.4.preinst b/debian/mariadb-server-10.4.preinst
--- a/debian/mariadb-server-10.4.preinst
+++ b/debian/mariadb-server-10.4.preinst
@@ -20,25 +20,25 @@ mysql_upgradedir=/var/lib/mysql-upgrade
 # do it himself. No database directories should be removed while the server
 # is running! Another mysqld in e.g. a different chroot is fine for us.
 stop_server() {
-    # Return immediately if there are no mysql processes running on a host
-    # (leave containerized processes with the same name in other namespaces)
-    # as there is no point in trying to shutdown in that case.
-    # Compatibility with versions that ran 'mariadbd'
-    if ! pgrep -x --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
+  # Return immediately if there are no mysql processes running on a host
+  # (leave containerized processes with the same name in other namespaces)
+  # as there is no point in trying to shutdown in that case.
+  # Compatibility with versions that ran 'mariadbd'
+  if ! pgrep -x --nslist pid --ns $$ "mysqld|mariadbd" > /dev/null; then return; fi
 
-    set +e
-    systemctl stop mysql
-    errno=$?
-    set -e
+  set +e
+  invoke-rc.d mysql stop
+  errno=$?
+  set -e
 
-    # 0=ok, 100=no init script (fresh install)
-    if [ "$errno" != 0 -a "$errno" != 100 ]; then
-      echo "'systemctl stop mysql' returned $errno" 1>&2
-      echo "There is a MySQL server running, but we failed in our attempts to stop it." 1>&2
-      echo "Stop it yourself and try again!" 1>&2
-      db_stop
-      exit 1
-    fi
+  # 0=ok, systemctl could emit exit code 100=no init script (fresh install)
+  if [ "$errno" != 0 -a "$errno" != 100 ]; then
+    echo "Attempt to stop MariaDB/MySQL server returned exitcode $errno" 1>&2
+    echo "There is a MariaDB/MySQL server running, but we failed in our attempts to stop it." 1>&2
+    echo "Stop it yourself and try again!" 1>&2
+    db_stop
+    exit 1
+  fi
 }
 
 ################################ main() ##########################
